A = int(input('Digite um número para obter sua tabuada: '))
print('--------------------------')
print('{} X  1 = {}'.format(A, A*1))
print('{} X  2 = {}'.format(A, A*2))
print('{} X  3 = {}'.format(A, A*3))
print('{} X  4 = {}'.format(A, A*4))
print('{} X  5 = {}'.format(A, A*5))
print('{} X  6 = {}'.format(A, A*6))
print('{} X  7 = {}'.format(A, A*7))
print('{} X  8 = {}'.format(A, A*8))
print('{} X  9 = {}'.format(A, A*9))
print('{} X 10 = {}'.format(A, A*10))
print('--------------------------')
